name: 'N3 Execution from Deploy'

on:
  workflow_run:
    workflows: ['N1 Manual Execution']
    types:
      - completed

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: E2E Test
        run: yarn cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: tests_reports
          path: ./cypress/reports/html

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Build feita com sucesso! âœ… \nStatus: `${{ job.status }}` \nAutor: @${{ github.actor }}"}' \
          $DISCORD_WEBHOOK_URL

